spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./tmp/customer
    username: sa
    password: null
  jpa: 
    hibernate:
      ddl-auto: validate
  thymeleaf:
    cache: false
security.basic.enabled: false
